### ISSUE TITLE
Issue when running main.py

### ISSUE THREAD

**Issue by lilyuam** [lukemelas/realfusion#15]
AttributeError: 'tuple' object has no attribute 'get_input_embeddings'

**Comment by lukemelas** [comment]
Can you post some more info about how/where you got this error?

**Comment by andrewyguo** [comment]
@lilyuam  Could this be related to this issue?  https://github.com/lukemelas/realfusion/issues/10

I was getting this error when using `diffusers==0.18.2` but I was able to resolve it after switching to `diffusers==0.15.0`.
