### ISSUE TITLE
Can it works on RTX3090?

### ISSUE THREAD

**Issue by SakuBorder** [lukemelas/realfusion#2]
I want to replicate your work. Can this method be executed on RTX3090

**Comment by lukemelas** [comment]
Hello, thanks for the issue. I have not run it on a RTX3090 and I do not have access to an RTX3090 for testing. If stable-dreamfusion can work on a 3090 (and I believe it can), then this should be able to work on one too.

**Comment by tydia** [comment]
I have successfully run training on a RTX3090. It takes about ~13G VRAM.

**Comment by lukemelas** [comment]
Thanks for confirming! 

Closing this issue. Feel free to re-open it if you have any unexpected issues specific to the 3090.

**Comment by SakuBorder** [comment]
> Hello, thanks for the issue. I have not run it on a RTX3090 and I do not have access to an RTX3090 for testing. If stable-dreamfusion can work on a 3090 (and I believe it can), then this should be able to work on one too.

Think you!I will have a try!

**Comment by SakuBorder** [comment]
> 

Thinks!

**Comment by SakuBorder** [comment]
> I have successfully run training on a RTX3090. It takes about ~13G VRAM.

Thinks!
